name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout private-scanner repo
      uses: actions/checkout@v2

    - name: Cache opencv.js
      id: cache-opencvjs
      uses: actions/cache@v2
      with:
        path: src/img-proc/opencv.js
        key: opencvjs

    - name: Checkout opencv repo
      if: steps.cache-opencvjs.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: opencv/opencv
        ref: 4.3.0
        token: ${{ secrets.PAT }}
        path: opencv

    - name: Build OpenCV.js
      if: steps.cache-opencvjs.outputs.cache-hit != 'true'
      run: |
        mv opencv_js.config.py opencv/platforms/js/opencv_js.config.py
        cd opencv
        docker run --rm --workdir /code -v "$PWD":/code "trzeci/emscripten:sdk-tag-1.38.32-64bit" python ./platforms/js/build_js.py build --build_wasm
        cd ${GITHUB_WORKSPACE}

    - name: Copy OpenCV.js into private-scanner project
      if: steps.cache-opencvjs.outputs.cache-hit != 'true'
      run: cp opencv/build/bin/opencv.js src/img-proc/opencv.js

    - name: Setup Node
      uses: actions/setup-node@v1

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node_modules

    - name: Install dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        yarn

    - name: Run tests and build
      run: |
        # yarn test # It seems that it is not possible to run test which save files on disk (see "remove sheet perspective")
        yarn build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
