name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout private-scanner repo
      uses: actions/checkout@v2
      with:
        path: private-scanner

    - name: Checkout opencv repo
      uses: actions/checkout@v2
      with:
        repository: opencv/opencv
        ref: 4.3.0
        token: ${{ secrets.PAT }}
        path: opencv

    - name: Build OpenCV.js
      run: |
        mv ${GITHUB_WORKSPACE}/private-scanner/opencv_js.config.py ${GITHUB_WORKSPACE}/opencv/platforms/js/opencv_js.config.py
        cd opencv
        docker run --rm --workdir /code -v "$PWD":/code "trzeci/emscripten:sdk-tag-1.38.32-64bit" python ./platforms/js/build_js.py build --build_wasm
        cd ${GITHUB_WORKSPACE}

    - name: Copy OpenCV.js into private-scanner project
      run: cp ${GITHUB_WORKSPACE}/opencv/build/bin/opencv.js ${GITHUB_WORKSPACE}/private-scanner/src/img-proc/opencv.js

    - name: Setup Node
      uses: actions/setup-node@v1

    - name: Install dependencies, run tests and build
      run: |
        cd ${GITHUB_WORKSPACE}/private-scanner
        yarn
        # yarn test # It seems that it is not possible to run test which save files on disk (see "remove sheet perspective")
        yarn build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./private-scanner/dist
